kind = "web"
previewPath = "/"
title = "Sistema de Biblioteca Escolar"
version = "1.0.0"
id = "artifacts/biblioteca"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
localPort = 25303
name = "web"
paths = ["/"]

[services.development]
run = "pnpm --filter @workspace/biblioteca run dev"

[services.env]
PORT = "25303"
BASE_PATH = "/"

[services.production]
build = ["pnpm", "--filter", "@workspace/biblioteca", "run", "build"]
publicDir = "artifacts/biblioteca/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"
